include ../../framework/makefiles/common.mk

BUNDLE_NAME := SDSettings
SDSettings_INSTALL_PATH = /Library/PreferenceBundles
SDSettings_BUNDLE_NAME = SafariDownloaderSettings

include ../../framework/makefiles/bundle.mk
