BUNDLE_NAME := SDSettings
SDSettings_FILES = SDSettings.mm

SDSettings_INSTALL_PATH = /System/Library/PreferenceBundles

SDSettings_FRAMEWORKS = UIKit CoreGraphics
SDSettings_PRIVATE_FRAMEWORKS = Preferences

SDSettings_CFLAGS = -I$(THEOS_PROJECT_DIR) -mthumb
SDSettings_LDFLAGS = -mthumb

SDSettings_BUNDLE_NAME = SafariDownloaderSettings

include ../framework/makefiles/common.mk
include ../framework/makefiles/bundle.mk
