BUNDLE_NAME := SDSettings
SDSettings_OBJCC_FILES = SDSettings.mm
SDSettings_OBJ_FILES = $(FRAMEWORKDIR)/lib/DHLocalizedListController.o

SDSettings_INSTALL_PATH = /System/Library/PreferenceBundles

SDSettings_FRAMEWORKS = UIKit CoreGraphics
SDSettings_PRIVATE_FRAMEWORKS = Preferences

SDSettings_CFLAGS = -mthumb
SDSettings_LDFLAGS = -mthumb

SDSettings_BUNDLE_NAME = SafariDownloaderSettings

include ../framework/makefiles/common.mk
include ../framework/makefiles/bundle.mk
