#!/bin/bash
if [[ $1 == configure ]]; then
	if [[ ! -f /var/mobile/Library/Preferences/net.howett.safaridownloader.plist ]]; then
		cp "/Library/Application Support/Safari Downloader/DefaultPrefs.plist" /var/mobile/Library/Preferences/net.howett.safaridownloader.plist
		chown mobile.mobile /var/mobile/Library/Preferences/net.howett.safaridownloader.plist
	fi
	if [[ -e /var/mobile/Library/Downloads ]]; then
		chown -R mobile.mobile /var/mobile/Library/Downloads
	fi
fi
