/**
 * This header is generated by class-dump-z 0.1-11p.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>

@class NSString, NSMutableArray;

@interface Alert : NSObject {
	NSString* _title;
	NSString* _bodyText;
	int _type;
	int _defaultAction;
	int _otherAction;
	int _hideAction;
	int _tableAction;
	NSMutableArray* _tableItems;
	int _indexOfSelectedTableItem;
	id _context;
}
-(id)initWithType:(int)type title:(id)title bodyText:(id)text defaultAction:(int)action otherAction:(int)action5 tableAction:(int)action6;
-(id)initWithType:(int)type title:(id)title defaultAction:(int)action otherAction:(int)action4 tableAction:(int)action5;
-(id)initWithType:(int)type title:(id)title bodyText:(id)text defaultAction:(int)action otherAction:(int)action5;
-(id)initWithType:(int)type title:(id)title defaultAction:(int)action otherAction:(int)action4;
-(void)dealloc;
-(int)type;
-(id)title;
-(id)bodyText;
-(id)_buttonTitleForAction:(int)action;
-(id)buttonTitles;
-(int)actionForButtonTag:(unsigned)buttonTag;
-(int)defaultAction;
-(int)hideAction;
-(int)tableAction;
-(void)setHideAction:(int)action;
-(void)setContext:(id)context;
-(id)context;
-(id)tableItems;
-(void)setTableItems:(id)items withTitles:(id)titles;
-(void)setSelectedTableItemIndex:(int)index;
-(id)selectedTableItem;
@end

