/**
 * This header is generated by class-dump-z 0.1-11p.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <UIKit/UIView.h>
#import "AuthenticationView.h"
#import "BrowserPanel.h"

@class NSURLAuthenticationChallenge, UINavigationBar, UIPreferencesTextTableCell, UITextLabel;

@interface AuthenticationView : UIView <BrowserPanel> {
	id _delegate;
	NSURLAuthenticationChallenge* _challenge;
	UINavigationBar* _navigationBar;
	UIPreferencesTextTableCell* _loginCell;
	UIPreferencesTextTableCell* _passwordCell;
	UITextLabel* _passwordSecurityLabel;
}
-(id)initWithDelegate:(id)delegate;
-(void)dealloc;
-(void)layoutSubviews;
-(id)challenge;
-(void)setChallenge:(id)challenge;
-(int)panelType;
-(int)panelState;
-(BOOL)allowsRotation;
-(BOOL)pausesPages;
-(void)didShowBrowserPanel;
-(void)didHideBrowserPanel;
-(BOOL)shouldHideOnSuspend;
-(void)navigationBar:(id)bar buttonClicked:(int)clicked;
@end

@interface AuthenticationView (Internal)
-(void)_focusPasswordField;
-(void)_logIn;
-(void)_cancel;
@end

