/**
 * This header is generated by class-dump-z 0.1-11p.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "NSObject.h"

@protocol BrowserPanel <NSObject>
-(int)panelType;
-(int)panelState;
-(BOOL)allowsRotation;
-(BOOL)pausesPages;
@end

