/**
 * This header is generated by class-dump-z 0.1-11p.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "BrowserPanel.h"
#import "WebUI-Structs.h"
#import "UIModalViewDelegate.h"
#import <Foundation/NSObject.h>

@class UIModalView;

@interface SheetController : NSObject <BrowserPanel, UIModalViewDelegate> {
	CFDictionaryRef _sheets;
	UIModalView* _sheet;
	id _delegate;
	int _actionToPerform;
}
-(id)initWithDelegate:(id)delegate;
-(void)dealloc;
-(int)panelType;
-(int)panelState;
-(BOOL)allowsRotation;
-(BOOL)pausesPages;
-(void)_showSheetForAlert:(id)alert inView:(id)view withClass:(Class)aClass;
-(void)showSheetForAlert:(id)alert inView:(id)view;
-(int)numberOfRowsInTable:(id)table;
-(id)table:(id)table cellForRow:(int)row column:(id)column;
-(void)tableSelectionDidChange:(id)tableSelection;
-(void)hideSheet;
-(void)setDelegate:(id)delegate;
-(void)alertSheet:(id)sheet buttonClicked:(int)clicked;
-(void)didDismissAlertSheet:(id)sheet;
@end

