/**
 * This header is generated by class-dump-z 0.1-11p.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <UIKit/UINavigationBar.h>


@interface UINavigationBar (UIKitExtras)
+(id)standardNavigationBar;
+(id)standardNavigationBarWithTitle:(id)title;
-(id)pushNavigationItemWithTitle:(id)title;
@end

