/**
 * This header is generated by class-dump-z 0.1-11p.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "WebUI-Structs.h"
#import <UIKit/UITable.h>


@interface UITable (UIKitExtras)
+(id)standardTableWithFrame:(CGRect)frame;
@end

