/**
 * This header is generated by class-dump-z 0.1-11p.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <UIKit/UIView.h>


@interface UIView (UIKitExtras)
-(void)fadeToAlpha:(float)alpha withDuration:(float)duration;
@end

