/**
 * This header is generated by class-dump-z 0.1-11p.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <WebKit/WebSecurityOrigin.h>


@interface WebSecurityOrigin (SafariExtras)
-(id)safari_userVisibleName;
@end

