/**
 * This header is generated by class-dump-z 0.1-11p.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>

@class NSString, NSMutableDictionary;

@interface WebUIGeolocationSupport : NSObject {
	NSMutableDictionary* _sites;
	BOOL _allowed;
	int _challengeCount;
	NSString* _key;
}
+(id)sharedWebUIGeolocationSupport;
-(id)siteFile;
-(void)load;
-(void)save;
-(void)clear;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(BOOL)webView:(id)view frame:(id)frame requestGeolocationPermissionForSecurityOrigin:(id)securityOrigin shouldClearCache:(BOOL)cache;
@end

