/**
 * This header is generated by class-dump-z 0.1-11p.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>


@interface WebUILocalStorageSupport : NSObject {
}
+(id)sharedWebUILocalStorageSupport;
-(id)localStoragePath;
-(unsigned)localStorageQuotaSize;
@end

