/**
 * This header is generated by class-dump-z 0.1-11p.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

typedef struct _NSZone NSZone;

//typedef struct __CFDictionary* CFDictionaryRef;

//typedef struct __SecPolicy* SecPolicyRef;

//typedef struct CGPoint {
//	float _field1;
//	float _field2;
//} CGPoint;

//typedef struct CGSize {
//	float _field1;
//	float _field2;
//} CGSize;

//typedef struct CGRect {
//	CGPoint _field1;
//	CGSize _field2;
//} CGRect;


